// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFscc3GRmZLtHxTICwb5LIgaG6ugmgvs',
    appId: '1:36589691175:web:2be87178edb4867d400902',
    messagingSenderId: '36589691175',
    projectId: 'daleeli-ff08a',
    authDomain: 'daleeli-ff08a.firebaseapp.com',
    storageBucket: 'daleeli-ff08a.firebasestorage.app',
    measurementId: 'G-ZDFH4WHD97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmYoWotYVpq-oAtRuDHnCJLbNz0QV76fk',
    appId: '1:36589691175:android:13c50d0b7d6c0f44400902',
    messagingSenderId: '36589691175',
    projectId: 'daleeli-ff08a',
    storageBucket: 'daleeli-ff08a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIGairvxJPyUBmklM-ck1_-KBknufgKuI',
    appId: '1:36589691175:ios:280c2d925af18f8b400902',
    messagingSenderId: '36589691175',
    projectId: 'daleeli-ff08a',
    storageBucket: 'daleeli-ff08a.firebasestorage.app',
    iosBundleId: 'com.example.daleeli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIGairvxJPyUBmklM-ck1_-KBknufgKuI',
    appId: '1:36589691175:ios:280c2d925af18f8b400902',
    messagingSenderId: '36589691175',
    projectId: 'daleeli-ff08a',
    storageBucket: 'daleeli-ff08a.firebasestorage.app',
    iosBundleId: 'com.example.daleeli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAFscc3GRmZLtHxTICwb5LIgaG6ugmgvs',
    appId: '1:36589691175:web:0ed74114384355d5400902',
    messagingSenderId: '36589691175',
    projectId: 'daleeli-ff08a',
    authDomain: 'daleeli-ff08a.firebaseapp.com',
    storageBucket: 'daleeli-ff08a.firebasestorage.app',
    measurementId: 'G-5M5G7P656Y',
  );
}
